# Change these first
owner: dgtl-llc # Your GitHub username
repo: uptime # Your GitHub repository name

# Add your sites here
sites:
  - name: DGTL.TECH Website
    url: $CDN_DGTLTECH
  - name: moon.dgtlnet.com
    url: https://moon.dgtlnet.com
  - name: Network Block List
    url: https://networkbl.com/
  - name: Billing system - DGTL TECH UK
    url: $BILL_URL
  - name: Billing system - DGTL Technologies LLC
    url: $BILLING_URL
  - name: MyMail Node [RU]
    url: $MYMAIL_RU_SITE
  - name: TCP ping
    url: 1.1.1.1
  - name: Google
    url: https://www.google.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.dgtl.tech
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://dgtl.tech/img/22e41419c90bf774e9f50bf7736821db.png
  name: DGTL.TECH STATUS
  introTitle: "Real-time uptime monitor by **DGTL.TECH**"
  introMessage: This status page shows the availability of our Services.
  navbar:
    - title: Status
      href: /
    - title: DGTL.TECH
      href: https://dgtl.tech

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
